#!/bin/bash

javac Syllables.java
OUTPUT="$(java Syllables < input.txt)"
LINESOUT="$(echo "${OUTPUT}" | nl)"
DIFF="$(diff <(echo "${LINESOUT}") <(nl output.txt) | grep ">")"
IFS=$'\n'; array=($DIFF);unset IFS;


for element in "${array[@]}"
do
    LINE="$(echo "$element" | sed -e '$!d' | grep -o -E '[0-9]+' | head -1)"
    NEWOUT="$(cat input.txt | nl | grep "\s${LINE}\s")"
    echo "${NEWOUT}"
    
done
echo "${DIFF}" | nl | sed -e '$!d' | grep -o -E '[0-9]+' | head -1

# echo "${LINESOUT}"
# diff <(${LINESOUT}) <(nl output.txt)

